site_name: Jane
repo_url: https://github.com/krischer/jane/
use_directory_urls: false
theme: cosmo
copyright: Jane Developers, 2014-2016
pages:
- 'Home': 'index.md'
- 'Introduction': 'introduction.md'
- 'Details':
    - 'Setup': 'setup.md'
    - 'Testing': 'testing.md'
    - 'Settings': 'settings.md'
    - 'Internals': 'internals.md'
    - 'REST Interface': 'rest.md'
    - 'Waveforms': 'waveforms.md'
    - 'Document Database': 'documents.md'
    - 'Management Commands': 'management_commands.md'
